In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../raw_data/clean_data.csv")

In [3]:
df.columns

# Step 1: Drop rows where the club is equal to 'Other'
df = df[df['club'] != 'Other']

def filter_position(df, club, position, max_count):
    filtered_df = df[(df['club'] == club) & (df[position] == 1)]
    return filtered_df.head(max_count)

def filter_and_append(avg_clubs, df, club, position, max_count):
    filtered_df = filter_position(df, club, position, max_count)
    return pd.concat([avg_clubs, filtered_df])

avg_clubs = pd.DataFrame()

for club in df['club'].unique():
    avg_clubs = filter_and_append(avg_clubs, df, club, 'goalkeeper', 2)
    avg_clubs = filter_and_append(avg_clubs, df, club, 'centerback', 3)
    avg_clubs = filter_and_append(avg_clubs, df, club, 'fullback', 4)
    avg_clubs = filter_and_append(avg_clubs, df, club, 'winger', 4)
    avg_clubs = filter_and_append(avg_clubs, df, club, 'midfielder', 5)
    avg_clubs = filter_and_append(avg_clubs, df, club, 'striker', 2)

In [4]:
df = avg_clubs.groupby(by='club').mean()

df.sort_values(by='club_rating', ascending=False, inplace=True)

In [5]:
def create_grouped_features(df):
    # Offensive Skills
    df['shooting'] = df[['fin', 'lon', 'fre', 'pen']].mean(axis=1)
    df['dribbling_control'] = df[['dri', 'fir', 'fla', 'tec']].mean(axis=1)
    df['passing_vision'] = df[['pas', 'vis', 'l th', 'cro', 'cor', 'otb']].mean(axis=1)
    
    # Defensive Skills
    df['tackling_interception'] = df[['tck', 'mar', 'pos', 'ant']].mean(axis=1)
    df['aerial_defense'] = df[['hea', 'jum', 'aer']].mean(axis=1)
    
    # Physical Attributes
    df['speed_agility'] = df[['acc', 'pac', 'agi']].mean(axis=1)
    df['strength_stamina'] = df[['str', 'sta', 'bal']].mean(axis=1)
    
    # Mental and Tactical Attributes
    df['decision_making'] = df[['dec', 'cmp']].mean(axis=1)
    df['work_ethic_effort'] = df[['wor', 'det', 'bra']].mean(axis=1)
    
    # Leadership and Teamwork
    df['leadership'] = df[['ldr', 'com']].mean(axis=1)
    df['teamwork'] = df['tea']
    
    # Goalkeeping Abilities
    df['goalkeeping_abilities'] = df[['han', 'ref', 'kic', 'thr', '1v1', 'ecc', 'cmd']].mean(axis=1)
    
    # Behavioral Attributes
    df['behavioral_attributes'] = df[['agg', 'pun']].mean(axis=1)
    
    # Player Traits
    df['player_traits'] = df['tro']
    
    # Create a new DataFrame with the grouped features
    dfgf = df[['shooting', 'dribbling_control', 'passing_vision', 'tackling_interception', 
               'aerial_defense', 'speed_agility', 'strength_stamina', 'decision_making', 
               'work_ethic_effort', 'leadership', 'teamwork', 'goalkeeping_abilities', 
               'behavioral_attributes', 'player_traits', 'club_rating']]
    
    return dfgf

In [6]:
df = create_grouped_features(df)

In [7]:
df

,shooting,dribbling_control,passing_vision,tackling_interception,aerial_defense,speed_agility,strength_stamina,decision_making,work_ethic_effort,leadership,teamwork,goalkeeping_abilities,behavioral_attributes,player_traits,club_rating
club,,,,,,,,,,,,,,,
Liverpool,9.437500,13.975000,11.533333,12.312500,8.366667,14.366667,13.850000,14.175000,14.616667,7.175000,14.500000,3.342857,8.425000,3.250000,2042.0
Man City,10.500000,13.937500,11.558333,10.750000,8.250000,14.733333,13.666667,13.825000,13.850000,6.550000,13.900000,3.392857,7.525000,3.300000,2013.0
R. Madrid,10.187500,13.512500,11.083333,10.975000,8.333333,13.933333,13.016667,12.775000,13.766667,6.800000,12.900000,3.200000,7.125000,2.850000,2010.0
FC Bayern,9.937500,12.037500,10.600000,10.400000,8.016667,13.783333,12.966667,14.000000,13.616667,6.450000,13.650000,3.278571,7.200000,3.900000,1955.0
Inter,10.013889,12.069444,10.250000,11.013889,8.444444,13.500000,13.481481,12.944444,14.296296,7.333333,14.611111,3.277778,7.861111,3.500000,1917.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Goian√©sia,6.263158,8.618421,7.219298,9.013158,6.789474,11.807018,9.280702,9.815789,10.228070,5.921053,8.631579,2.932331,6.815789,2.947368,1156.0
Gold Coast Knights,5.928571,8.321429,6.761905,8.214286,5.428571,12.142857,7.880952,9.821429,9.857143,6.000000,8.285714,3.193878,6.285714,2.857143,1156.0
Gold Coast Utd (NPL),4.173077,6.807692,5.794872,8.096154,6.538462,11.051282,7.564103,9.076923,8.512821,5.346154,7.153846,2.582418,5.423077,2.615385,1156.0
Goldau,4.328947,7.447368,5.649123,7.157895,5.350877,12.368421,7.263158,8.842105,8.877193,5.052632,7.000000,2.969925,6.710526,3.368421,1156.0
≈Ωelezniƒçar (P),6.944444,9.291667,8.685185,9.222222,7.351852,11.537037,9.222222,10.777778,10.000000,6.305556,9.777778,3.047619,6.805556,2.555556,1156.0

In [14]:
counter_attacking_style = {
    'relevant_features': ['speed_agility', 'passing_vision', 'tackling_interception', 'shooting'],
    'weights': [0.40, 0.13, 0.12, 0.35]
}

# High-Pressing Havoc
high_pressing_style = {
    'relevant_features': ['speed_agility', 'tackling_interception', 'work_ethic_effort', 'decision_making'],
    'weights': [0.30, 0.25, 0.20, 0.25]
}

# Defensive Fortress
defensive_style = {
    'relevant_features': ['aerial_defense', 'strength_stamina', 'work_ethic_effort', 'tackling_interception'],
    'weights': [0.40, 0.18, 0.17, 0.25]
}

# Wing Dominance
wing_dominance_style = {
    'relevant_features': ['speed_agility', 'strength_stamina', 'decision_making', 'shooting'],
    'weights': [0.50, 0.10, 0.20, 0.20]
}

# Possession with Purpose
possession_with_purpose_style = {
    'relevant_features': ['teamwork', 'dribbling_control', 'passing_vision', 'decision_making'],
    'weights': [0.10, 0.35, 0.30, 0.25]
}

# Youthful Energy and High Intensity
youthful_energy_style = {
    'relevant_features': ['dribbling_control', 'speed_agility', 'strength_stamina', 'tackling_interception'],
    'weights': [0.35, 0.40, 0.10, 0.15]
}

# Midfield Maestros
midfield_maestros_style = {
    'relevant_features': ['decision_making', 'leadership', 'player_traits', 'behavioral_attributes'],
    'weights': [0.35, 0.20, 0.35, 0.10]
}

In [15]:
styles = {
    'counter_attack': counter_attacking_style, 
    'high_pressing': high_pressing_style, 
    'defensive': defensive_style, 
    'midfield_maestros': midfield_maestros_style,
    'wing_dominance': wing_dominance_style, 
    'possession_with_purpose': possession_with_purpose_style,
    'youthful_energy': youthful_energy_style}

In [16]:
def calculate_team_score(df, playing_style):
    relevant_features = playing_style['relevant_features']
    weights = playing_style['weights']

    # Filter DataFrame to include only relevant features
    relevant_df = df[relevant_features]

    # Normalize the relevant features to have values between 0 and 1
    normalized_df = (relevant_df - relevant_df.min()) / (relevant_df.max() - relevant_df.min())

    # Calculate the weighted sum for each team
    team_scores = (normalized_df * weights).sum(axis=1)
    
    # Making a DataFrame
    team_scores = pd.DataFrame(team_scores).sort_values(by=0, axis=0, ascending=False)

    # Get the team with the highest score
    best_team = team_scores.idxmax()

    return best_team, team_scores

# Create a DataFrame to store style scores for each team
all_style_scores = pd.DataFrame(index=df.index)

# Calculate the best team for each style and store the scores in the DataFrame
for style_name, style in styles.items():
    best_team, team_scores = calculate_team_score(df, style)
    
    # Renaming column
    team_scores = team_scores.rename(columns={0: style_name})
    
    # Merge the style scores with the overall DataFrame
    all_style_scores = pd.merge(all_style_scores, team_scores, left_index=True, right_index=True, how='outer')

    print(f"Best team for {style_name}: {best_team}")

# Calculate the average score for each team across all styles
all_style_scores['average_score'] = all_style_scores.mean(axis=1)

# Sort by the best average score
all_style_scores = all_style_scores.sort_values(by='average_score', ascending=False)


all_style_scores

Best team for counter_attack: 0    Man City
dtype: object
Best team for high_pressing: 0    Liverpool
dtype: object
Best team for defensive: 0    Tottenham
dtype: object
Best team for midfield_maestros: 0    FC Bayern
dtype: object
Best team for wing_dominance: 0    Man City
dtype: object
Best team for possession_with_purpose: 0    Barcelona
dtype: object
Best team for youthful_energy: 0    Liverpool
dtype: object

,counter_attack,high_pressing,defensive,midfield_maestros,wing_dominance,possession_with_purpose,youthful_energy,average_score
club,,,,,,,,
Liverpool,0.922248,0.982980,0.963931,0.851419,0.941774,0.980062,0.968911,0.944475
Man City,0.960807,0.927591,0.894681,0.793193,0.980067,0.965545,0.959047,0.925847
Barcelona,0.931698,0.900748,0.808398,0.842987,0.940310,0.990866,0.927627,0.906090
A. Madrid,0.913406,0.929168,0.903512,0.816442,0.904169,0.946050,0.880144,0.898984
Zebre,0.892233,0.879994,0.930284,0.805044,0.893205,0.908498,0.890666,0.885703
...,...,...,...,...,...,...,...,...
Rimba Star,0.180289,0.197173,0.061638,0.385825,0.226027,0.076883,0.187739,0.187939
Setia Perdana,0.202091,0.171488,0.069912,0.254471,0.264674,0.051176,0.227106,0.177274
Kelantan Tumpat,0.159203,0.167016,0.123940,0.280647,0.187112,0.117818,0.174076,0.172830
Tunas,0.168541,0.142632,0.123129,0.298601,0.230659,0.048257,0.180392,0.170316
Besa FC,0.183692,0.160412,0.128886,0.293026,0.207212,0.021667,0.193432,0.169761

In [11]:
### positions dataframe

def custom_scaler(dfgf_no_name):
    total_score = dfgf_no_name.sum(axis=1)
    scaled_dfgf_no_name = dfgf_no_name.div(total_score, axis=0)
    return scaled_dfgf_no_name

In [12]:
df = custom_scaler(df)

In [13]:
# Create a DataFrame to store style scores for each team
all_style_scores = pd.DataFrame(index=df.index)

# Calculate the best team for each style and store the scores in the DataFrame
for style_name, style in styles.items():
    best_team, team_scores = calculate_team_score(df, style)
    
    # Renaming column
    team_scores = team_scores.rename(columns={0: style_name})
    
    # Merge the style scores with the overall DataFrame
    all_style_scores = pd.merge(all_style_scores, team_scores, left_index=True, right_index=True, how='outer')

    print(f"Best team for {style_name}: {best_team}")

# Calculate the average score for each team across all styles
all_style_scores['average_score'] = all_style_scores.mean(axis=1)

# Sort by the best average score
all_style_scores = all_style_scores.sort_values(by='average_score', ascending=False)


all_style_scores

Best team for counter_attack: 0    Zebre
dtype: object
Best team for high_pressing: 0    Zebre
dtype: object
Best team for defensive: 0    Zebre
dtype: object
Best team for midfield_maestros: 0    Real San Sebasti√°n
dtype: object
Best team for wing_dominance: 0    Zebre
dtype: object
Best team for possession_with_purpose: 0    Zebre
dtype: object
Best team for youthful_energy: 0    Zebre
dtype: object

,counter_attack,high_pressing,defensive,midfield_maestros,wing_dominance,possession_with_purpose,youthful_energy,average_score
club,,,,,,,,
Zebre,0.978310,0.969344,0.956253,0.837902,0.993466,0.988688,0.992054,0.959431
Real Hispalis,0.931668,0.926818,0.903329,0.776169,0.930120,0.960371,0.935987,0.909209
Real San Sebasti√°n,0.908683,0.924749,0.923035,0.871003,0.910644,0.886717,0.884270,0.901300
SPO,0.962344,0.915836,0.871658,0.791074,0.947450,0.901931,0.896906,0.898171
SEP,0.953514,0.901352,0.861052,0.767967,0.938136,0.901390,0.924197,0.892515
...,...,...,...,...,...,...,...,...
Llangefni,0.235779,0.247652,0.189527,0.273605,0.309692,0.166141,0.263596,0.240856
Legan√©s B,0.259778,0.196456,0.269011,0.159084,0.246215,0.276257,0.247038,0.236263
Besa FC,0.250136,0.295457,0.179410,0.333981,0.277863,0.026865,0.257184,0.231556
Tunas,0.225240,0.269158,0.160440,0.346683,0.307483,0.059763,0.240426,0.229885
Kelantan Tumpat,0.206693,0.268301,0.162836,0.329484,0.244847,0.140958,0.225122,0.225463

In [14]:
df[df.index == 'Liverpool']

,shooting,dribbling_control,passing_vision,tackling_interception,aerial_defense,speed_agility,strength_stamina,decision_making,work_ethic_effort,leadership,teamwork,goalkeeping_abilities,behavioral_attributes,player_traits,club_rating
club,,,,,,,,,,,,,,,
Liverpool,0.004307,0.006377,0.005263,0.005619,0.003818,0.006556,0.00632,0.006469,0.00667,0.003274,0.006617,0.001525,0.003845,0.001483,0.931856