#  import modules

In [1]:
import numpy as np
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

#  import data

In [2]:
df = pd.read_csv("../raw_data/FM_data_21.csv", low_memory = False)

#  data cleaning

###  data exploration

In [3]:
df.head(20)

,Name,Club,Nat,Division,Position,Sec. Position,DoB,Age,Preferred Foot,Right Foot,...,Bal,Kic,Sta,Agi,Wor,Bra,Cmd,Fin,1v1,TRO
0,Kevin De Bruyne,Man City,BEL,English Premier Division ...,"M (RLC), AM (C)",M (RL),28/6/1991 (29 years old),29,Either,Very Strong,...,15,3,17,13,15,12,3,16,1,3
1,Harry Kane,Tottenham,ENG,English Premier Division ...,"AM (C), ST (C)",AM (C),28/7/1993 (27 years old),26,Either,Very Strong,...,13,3,17,12,18,16,2,19,3,3
2,Mohamed Salah,Liverpool,EGY,English Premier Division ...,"AM (RL), ST (C)",AM (L),15/6/1992 (28 years old),28,Left,Weak,...,18,1,14,16,15,11,3,18,3,2
3,Sadio Man√©,Liverpool,SEN,English Premier Division ...,"AM (RL), ST (C)",ST (C),10/4/1992 (28 years old),28,Right,Very Strong,...,16,1,14,16,15,11,3,17,2,4
4,Son Heung-Min,Tottenham,KOR,English Premier Division ...,"M/AM (RL), ST (C)","M (RL), AM (R)",8/7/1992 (28 years old),28,Either,Very Strong,...,12,2,16,15,17,6,2,18,2,1
5,Raheem Sterling,Man City,ENG,English Premier Division ...,M/AM (RL),M (RL),8/12/1994 (25 years old),25,Right,Very Strong,...,15,3,17,19,16,11,3,13,3,3
6,Bernardo Silva,Man City,POR,English Premier Division ...,M/AM (RC),M (R),10/8/1994 (25 years old),25,Left,Weak,...,18,3,16,19,20,15,2,16,4,2
7,Roberto Firmino,Liverpool,BRA,English Premier Division ...,"AM (RLC), ST (C)",AM (RL),2/10/1991 (28 years old),28,Right,Very Strong,...,17,3,16,15,18,13,3,13,4,3
8,Virgil van Dijk,Liverpool,NED,English Premier Division ...,D (C),-,8/7/1991 (29 years old),29,Right,Very Strong,...,15,2,14,12,12,15,2,8,1,2
9,Bruno Fernandes,Man Utd,POR,English Premier Division ...,M/AM (C),-,8/9/1994 (25 years old),25,Right,Very Strong,...,14,2,18,15,17,17,2,15,1,1
10,Aymeric Laporte,Man City,FRA,English Premier Division ...,D (C),-,27/5/1994 (26 years old),26,Left,Reasonable,...,14,3,14,13,14,15,4,8,3,3
11,Paul Pogba,Man Utd,FRA,English Premier Division ...,M/AM (C),AM (C),15/3/1993 (27 years old),27,Right,Very Strong,...,18,3,18,14,11,9,1,14,3,1
12,Sergio Ag√ºero,Man City,ARG,English Premier Division ...,"AM (C), ST (C)",AM (C),2/6/1988 (32 years old),32,Either,Very Strong,...,20,1,16,18,13,14,1,17,1,1
13,Thiago,Liverpool,ESP,English Premier Division ...,"DM, M/AM (C)",AM (C),11/4/1991 (29 years old),29,Right,Very Strong,...,13,3,15,17,15,11,3,10,2,2
14,Fabinho,Liverpool,BRA,English Premier Division ...,"D (RC), DM, M (C)","D (R), M (C)",23/10/1993 (26 years old),26,Right Only,Very Strong,...,14,1,15,14,16,15,3,7,1,2
15,ƒ∞lkay G√ºndogan,Man City,GER,English Premier Division ...,"DM, M/AM (C)","DM, AM (C)",24/10/1990 (29 years old),29,Right,Very Strong,...,14,2,15,16,14,12,1,12,1,3
16,Trent Alexander-Arnold,Liverpool,ENG,English Premier Division ...,"D/WB (R), DM, M (C)","DM, M (C)",7/10/1998 (21 years old),21,Right,Very Strong,...,14,1,14,14,15,14,3,10,2,1
17,Alisson,Liverpool,BRA,English Premier Division ...,GK,-,2/10/1992 (27 years old),27,Right,Very Strong,...,16,16,12,15,15,14,13,2,18,16
18,Jack Grealish,Aston Villa,ENG,English Premier Division ...,M/AM (RLC),M/AM (R),10/9/1995 (24 years old),24,Right,Very Strong,...,14,2,13,15,15,13,2,15,3,2
19,R√∫ben Dias,Man City,POR,English Premier Division ...,D (C),-,14/5/1997 (23 years old),23,Right,Very Strong,...,15,1,16,13,16,18,2,6,2,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174574 entries, 0 to 174573
Data columns (total 66 columns):
 #   Column                                                Non-Null Count   Dtype
---  ------                                                --------------   -----
 0    Name                                                 174574 non-null  object
 1    Club                                                 174574 non-null  object
 2    Nat                                                  174574 non-null  object
 3    Division                                             174574 non-null  object
 4    Position                                             174574 non-null  object
 5    Sec. Position                                        174574 non-null  object
 6    DoB                                                  174574 non-null  object
 7    Age                                                  174574 non-null  object
 8    Preferred Foot                                       174574 non-null  object
 9    Right Foot                                           174574 non-null  object
 10   Left Foot                                            174574 non-null  object
 11   Height                                               174574 non-null  object
 12   Weight                                               174574 non-null  object
 13   AT Lge Gls                                           174574 non-null  object
 14   AT Lge Apps                                          174574 non-null  object
 15   Wage                                                 174574 non-null  object
 16   Last Trans. Fee                                      174574 non-null  object
 17   Value                                                174574 non-null  object
 18   Rc Injury                                            174574 non-null  object
 19   Agg                                                  174574 non-null  object
 20   Jum                                                  174574 non-null  object
 21   Pun                                                  174574 non-null  object
 22   Nat .1                                               174574 non-null  object
 23   Vis                                                  174574 non-null  object
 24   L Th                                                 174574 non-null  object
 25   Lon                                                  174574 non-null  object
 26   OtB                                                  174574 non-null  object
 27   Tck                                                  174574 non-null  object
 28   Tec                                                  174574 non-null  object
 29   Tea                                                  174574 non-null  object
 30   Cmp                                                  174574 non-null  object
 31   Fre                                                  174574 non-null  object
 32   Ref                                                  174574 non-null  object
 33   Pos                                                  174574 non-null  object
 34   Pen                                                  174574 non-null  object
 35   Pas                                                  174574 non-null  object
 36   Fla                                                  174574 non-null  object
 37   Ant                                                  174574 non-null  object
 38   Cro                                                  174574 non-null  object
 39   Mar                                                  174574 non-null  object
 40   Ldr                                                  174574 non-null  object
 41   Cor                                                  174574 non-null  object
 42   Cnt                                                  174574 non-null  object
 43   Det                                                  174574 non-null  object
 44   Dec                                                  174574 non-null  object
 45   Hea                                                  174574 non-null  object
 46   Fir                                                  174574 non-null  object
 47   Com                                                  174574 non-null  object
 48   Acc                                                  174574 non-null  object
 49   Pac                                                  174574 non-null  object
 50   Aer                                                  174574 non-null  object
 51   Str                                                  174574 non-null  object
 52   Thr                                                  174574 non-null  object
 53   Han                                                  174574 non-null  object
 54   Ecc                                                  174574 non-null  object
 55   Dri                                                  174574 non-null  object
 56   Bal                                                  174574 non-null  object
 57   Kic                                                  174574 non-null  object
 58   Sta                                                  174574 non-null  object
 59   Agi                                                  174574 non-null  object
 60   Wor                                                  174574 non-null  object
 61   Bra                                                  174574 non-null  object
 62   Cmd                                                  174574 non-null  object
 63   Fin                                                  174574 non-null  object
 64   1v1                                                  174574 non-null  object
 65   TRO                                                  174574 non-null  object
dtypes: object(66)
memory usage: 87.9+ MB

### basic cleaning

In [5]:
# cleaning column names

df.rename(str.lower, axis='columns', inplace = True)
df.rename(str.strip, axis='columns', inplace = True)

In [6]:
# cleaning columns with strings

df.name = df.name.str.strip()
df.division = df.division.str.strip()
df.nat = df.nat.str.strip()
df.club = df.club.str.strip()
df["preferred foot"] = df["preferred foot"].str.strip()
df["left foot"] = df["left foot"].str.strip()
df["right foot"] = df["right foot"].str.strip()

In [7]:
# Drop rows with empty string in the 'name' column
df = df[df["name"] != ""]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 174324 entries, 0 to 174573
Data columns (total 66 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   name             174324 non-null  object
 1   club             174324 non-null  object
 2   nat              174324 non-null  object
 3   division         174324 non-null  object
 4   position         174324 non-null  object
 5   sec. position    174324 non-null  object
 6   dob              174324 non-null  object
 7   age              174324 non-null  object
 8   preferred foot   174324 non-null  object
 9   right foot       174324 non-null  object
 10  left foot        174324 non-null  object
 11  height           174324 non-null  object
 12  weight           174324 non-null  object
 13  at lge gls       174324 non-null  object
 14  at lge apps      174324 non-null  object
 15  wage             174324 non-null  object
 16  last trans. fee  174324 non-null  object
 17  value            174324 non-null  object
 18  rc injury        174324 non-null  object
 19  agg              174324 non-null  object
 20  jum              174324 non-null  object
 21  pun              174324 non-null  object
 22  nat .1           174324 non-null  object
 23  vis              174324 non-null  object
 24  l th             174324 non-null  object
 25  lon              174324 non-null  object
 26  otb              174324 non-null  object
 27  tck              174324 non-null  object
 28  tec              174324 non-null  object
 29  tea              174324 non-null  object
 30  cmp              174324 non-null  object
 31  fre              174324 non-null  object
 32  ref              174324 non-null  object
 33  pos              174324 non-null  object
 34  pen              174324 non-null  object
 35  pas              174324 non-null  object
 36  fla              174324 non-null  object
 37  ant              174324 non-null  object
 38  cro              174324 non-null  object
 39  mar              174324 non-null  object
 40  ldr              174324 non-null  object
 41  cor              174324 non-null  object
 42  cnt              174324 non-null  object
 43  det              174324 non-null  object
 44  dec              174324 non-null  object
 45  hea              174324 non-null  object
 46  fir              174324 non-null  object
 47  com              174324 non-null  object
 48  acc              174324 non-null  object
 49  pac              174324 non-null  object
 50  aer              174324 non-null  object
 51  str              174324 non-null  object
 52  thr              174324 non-null  object
 53  han              174324 non-null  object
 54  ecc              174324 non-null  object
 55  dri              174324 non-null  object
 56  bal              174324 non-null  object
 57  kic              174324 non-null  object
 58  sta              174324 non-null  object
 59  agi              174324 non-null  object
 60  wor              174324 non-null  object
 61  bra              174324 non-null  object
 62  cmd              174324 non-null  object
 63  fin              174324 non-null  object
 64  1v1              174324 non-null  object
 65  tro              174324 non-null  object
dtypes: object(66)
memory usage: 89.1+ MB

In [9]:
df = df.reset_index(drop=True)

In [21]:
df['at lge apps'].unique()

array(['337', '263', '288', '279', '301', '259', '245', '353', '289',
       '234', '261', '235', '491', '268', '254', '258', '93', '148',
       '196', '146', '142', '305', '149', '194', '216', '172', '350',
       '383', '197', '183', '236', '233', '225', '401', '326', '41',
       '324', '121', '179', '150', '174', '186', '201', '175', '297',
       '341', '309', '293', '83', '182', '349', '193', '300', '91', '205',
       '163', '120', '165', '125', '199', '209', '283', '71', '240',
       '117', '34', '27', '133', '153', '217', '124', '155', '156', '128',
       '152', '230', '138', '151', '264', '319', '58', '211', '208',
       '243', '335', '219', '250', '157', '181', '115', '276', '352',
       '166', '231', '99', '402', '282', '290', '96', '410', '204', '312',
       '221', '232', '238', '77', '9', '94', '139', '248', '31', '280',
       '103', '269', '368', '256', '66', '344', '40', '24', '136', '478',
       '237', '145', '426', '260', '267', '18', '180', '87', '314', '291',
       '222', '390', '167', '247', '13', '277', '164', '59', '382', '334',
       '43', '169', '284', '38', '122', '161', '408', '385', '118', '104',
       '137', '112', '366', '37', '191', '227', '158', '357', '454',
       '375', '63', '496', '272', '17', '132', '380', '33', '323', '315',
       '171', '398', '141', '249', '184', '360', '307', '98', '116',
       '242', '377', '22', '6', '74', '97', '215', '160', '76', '86',
       '140', '257', '67', '251', '317', '64', '275', '303', '105', '15',
       '70', '200', '176', '400', '213', '82', '3', '190', '367', '345',
       '437', '338', '430', '355', '389', '130', '53', '316', '192',
       '318', '162', '270', '292', '321', '92', '356', '262', '244',
       '347', '79', '47', '220', '224', '226', '114', '90', '308', '265',
       '394', '20', '223', '4', '480', '391', '310', '131', '441', '177',
       '26', '203', '287', '72', '144', '198', '189', '126', '336', '68',
       '342', '21', '5', '106', '246', '322', '218', '51', '298', '88',
       '207', '299', '57', '369', '143', '28', '46', '73', '119', '302',
       '135', '29', '483', '487', '159', '294', '278', '229', '187',
       '253', '100', '78', '44', '373', '214', '306', '195', '170', '371',
       '365', '147', '2', '75', '281', '313', '108', '286', '55', '45',
       '168', '185', '52', '111', '84', '25', '36', '330', '212',
       ' -           ', '107', '255', '95', '499', '339', '69', '109',
       '273', '56', '228', '435', '461', '113', '14', '7', '329', '178',
       '110', '173', '459', '494', '544', '134', '81', '346', '470', '85',
       '332', '11', '271', '23', '274', '48', '1', '348', '127', '80',
       '123', '252', '188', '239', '320', '364', '65', '32', '102', '384',
       '304', '343', '154', '42', '416', '49', '129', '411', '358', '457',
       '101', '19', '333', '10', '62', '12', '241', '54', '392', '421',
       '325', '285', '433', '452', '537', '328', '327', '206', '210',
       '361', '39', '89', '354', '370', '60', '376', '551', '331', '417',
       '482', '296', '456', '631', '472', '351', '8', '266', '295', '484',
       '340', '431', '202', '61', '35', '16', '50', '455', '374', '582',
       '498', '497', '311', '495', '439', '471', '30', '415', '363',
       '508', '600', '418', '453', '397', '396', '511', '462', '429',
       '403', '362', '574', '359', '460', '395', '434', '595', '381',
       '404', '432', '468', '446', '422', '438', '372', '589', '414',
       '387', '445', '579', '463', '405', '428', '425', '386', '399',
       '485', '436', '409', '420', '378', '388', '573', '529', '393',
       '407', '427', '443', '549', '412', '447', '451', '556', '444',
       '477', '448', '466', '517', '486', '539', '507', '476', '379',
       '502', '406', '440', '467', '570', '450', '413', '492', '548',
       '424', '475', '469', '545', '481', '442', '531', '474', '449',
       '560', '590', '423', '538', '473', '513', '542', '695', '505',
       '521', '547', '567', '519', '458', '504', '666', '526', '656',
       '681', '602', '645', '603', '604', '419', '629', '525', '522',
       '827', '533', '697', '503', '488', '557', '578', '553', '510',
       '563', '592', '509', '610', '550', '597', '464', '711', '638',
       '571', '588', '514', '512', '536', '591', '543', '523', '506',
       '527', '577', '637', '534', '641', '520', '552', '660', '587',
       '607', '518', '599', '479', '490', '541', '516', '493', '540',
       '575', '554', '530', '576', '601', '535', '572', '632', '566',
       '617', '501', '585', '581', '500', '524', '703', '626', '664',
       '623', '747', '639', '633', '515', '489', '465', '558', '770',
       '555', '568', '612', '644', '670', '559', '532', '586', '580',
       '546', '652', '583', '625', '528', '619', '680', '640', '676',
       '561', '678', '647', '613', '648'], dtype=object)

In [22]:
df[df['at lge apps'] == ' -           ']

,name,club,nat,division,position,sec. position,dob,age,preferred foot,right foot,...,bal,kic,sta,agi,wor,bra,cmd,fin,1v1,tro
623,Ethan Laird,MK Dons,ENG,Sky Bet League One,D/WB (RL),"D (L), WB (RL)",4/8/2001 (18 years old),18,Right,Very Strong,...,10,2,12,14,14,11,1,9,2,2
656,Illya Zabarnyi,Dynamo Kyiv,UKR,Ukrainian Premier League,D (C),-,1/9/2002 (17 years old),17,Right,Very Strong,...,10,2,8,12,10,11,3,7,2,3
722,Abdallah Sima,Slavia Prague,SEN,Czech First Division,AM (R),-,17/6/2001 (19 years old),19,Right,Very Strong,...,11,2,9,12,12,8,3,16,2,3
792,Folarin Balogun,Arsenal,ENG,English Premier Division,"AM (R), ST (C)",AM (R),3/7/2001 (19 years old),19,Right,Very Strong,...,12,2,12,15,13,10,1,14,1,1
1025,Owen Otasowie,Wolves,USA,English Premier Division,"D (C), DM, M (C)",D (C),20/4/2001 (19 years old),19,Right,Very Strong,...,15,1,11,13,13,13,2,5,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174319,Nick Brown,Charlotte FC Academy,USA,Lower Leagues,ST (C),-,13/12/2004 (15 years old),15,Right,Very Strong,...,13,1,10,10,15,9,1,14,2,3
174320,Luis Alcal√°,Charlotte FC Academy,USA,Lower Leagues,ST (C),-,11/5/2004 (16 years old),16,Right,Very Strong,...,11,2,8,9,6,6,2,11,2,3
174321,Devin Lee,Charlotte FC Academy,USA,Lower Leagues,D (C),-,4/4/2003 (17 years old),17,Right,Very Strong,...,16,1,12,8,17,13,2,5,2,1
174322,Yeferson Su√°rez,Charlotte FC Academy,USA,Lower Leagues,M (C),-,4/1/2004 (16 years old),16,Right Only,Very Strong,...,8,3,7,9,11,9,3,6,1,1
174323,Nguyen Van Hai,Charlotte FC Academy,VIE,Lower Leagues,AM (R),-,19/4/2004 (16 years old),16,Right Only,Very Strong,...,6,4,8,14,13,16,3,4,1,2

In [ ]:
# drop sec position column rc injury, at lge gls and at lge apps
df.drop(columns = ['sec. position', 'rc injury', 'at lge gls', 'at lge apps', 'nat .1'], inplace=True)

###  column definitions

In [ ]:
column_definitions = {
    'name': 'Player name',
    'club': 'Current club',
    'nat': 'Nationality',
    'division': 'Club division',
    'position': 'Primary playing position',
    'sec. position': 'Secondary playing position',
    'dob': 'Date of birth',
    'age': 'Player age',
    'preferred foot': 'Preferred foot for playing',
    'right foot': 'Right foot proficiency',
    'left foot': 'Left foot proficiency',
    'height': 'Player height',
    'weight': 'Player weight',
    'at lge gls': 'Goals scored in the league',
    'at lge apps': 'Appearances in the league',
    'wage': 'Players wage',
    'last trans. fee': 'Last transfer fee paid',
    'value': 'Players market value',
    'rc injury': 'Recovery from injury',
    'agg': 'Aggression attribute',
    'jum': 'Jumping attribute',
    'pun': 'Punishment attribute',
    'nat .1': 'Nationality (duplicate)',
    'vis': 'Vision attribute',
    'l th': 'Long throwing attribute',
    'lon': 'Long shots attribute',
    'otb': 'Off the ball attribute',
    'tck': 'Tackling attribute',
    'tec': 'Technique attribute',
    'tea': 'Teamwork attribute',
    'cmp': 'Composure attribute',
    'fre': 'Free-kick taking attribute',
    'ref': 'Reflexes attribute',
    'pos': 'Positioning attribute',
    'pen': 'Penalties attribute',
    'pas': 'Passing attribute',
    'fla': 'Flair attribute',
    'ant': 'Anticipation attribute',
    'cro': 'Crossing attribute',
    'mar': 'Marking attribute',
    'ldr': 'Leadership attribute',
    'cor': 'Corner-taking attribute',
    'cnt': 'Concentration attribute',
    'det': 'Determination attribute',
    'dec': 'Decision-making attribute',
    'hea': 'Heading attribute',
    'fir': 'First touch attribute',
    'com': 'Communication attribute',
    'acc': 'Acceleration attribute',
    'pac': 'Pace attribute',
    'aer': 'Aerial ability attribute',
    'str': 'Strength attribute',
    'thr': 'Throw-in attribute',
    'han': 'Handling attribute',
    'ecc': 'Eccentricity attribute',
    'dri': 'Dribbling attribute',
    'bal': 'Balance attribute',
    'kic': 'Kicking attribute',
    'sta': 'Stamina attribute',
    'agi': 'Agility attribute',
    'wor': 'Work rate attribute',
    'bra': 'Bravery attribute',
    'cmd': 'Command of area attribute',
    'fin': 'Finishing attribute',
    '1v1': 'One-on-one ability attribute',
    'tro': 'Traits attribute'
}

In [ ]:
df.info()

###  classing positions

In [ ]:
# copy position column to main_position
df["main_position"] = df.position

# removing the spaces in the string
df.main_position = df.main_position.str.strip().str.replace(',\s*', ',')
 
# making a list out of all the positions
df.main_position = df.main_position.str.split(',')

# peek
df.main_position.head()

In [ ]:
# dictionary for every position class
football_positions = {
    'goalkeeper': ['GK'],
    'centerback': ['D (C)', 'D (RC)', 'D (LC)', 'D (RLC)', 'D/M (C)'],
    'fullback': ['D/WB/AM (RL)','D/WB/AM (L)','WB/M/AM (L)','WB/M (R)','WB/M/AM (R)','D/WB/M/AM (R)','D/WB/M/AM (L)','D/WB/M (R)','WB (R)','WB/M/AM (RL)','D/WB/M (RL)','D/WB (RL)','WB (L)','D/WB/AM (R)','D/WB (L)','WB (RL)','D/WB (R)','D (RL)', 'D (L)', 'D (R)', 'D (L)', 'D/AM (R)', 'D/AM (L)', 'D/AM (RL)', 'D/WB/M (L)', 'D/M/AM (RL)', 'D/M/AM (L)', 'D/M (R)', 'D/M (L)', 'D/AM (R)', 'WB/M (L)', 'D/M/AM (R)', 'D/WB/M/AM (RL)', 'D/M (R)', 'D/M (L)', 'D/AM (R)', 'WB/AM (L)', 'D/AM (L)', 'D/AM (RL)', 'WB/M (RL)', 'WB/AM (R)', 'D/M (RL)', 'WB/AM (RL)'],
    'midfielder': ['D/M (RC)','D/M/AM (C)','D/AM (C)','D/M (LC)','D/M/AM (LC)','AM (LC)','AM (RLC)','AM (RC)','AM (C)','M (RLC)','M (C)', 'M (LC)', 'M (RC)', 'DM', 'M/AM (C)', 'M/AM (LC)', 'M/AM (RC)', 'M/AM (RLC)'],
    'winger': ['AM (RL)','M (RL)', 'M (R)', 'M (L)', 'M/AM (R)', 'M/AM (L)', 'M/AM (RL)', 'AM (L)', 'AM (R)'],
    'striker': ['ST (C)'],
    "no_position": [""]
}
# making the map with the football positions dictionary
positions_map = {}

for main_position, positions_list in football_positions.items():
    for position in positions_list:
        positions_map[position] = main_position


# peek
positions_map

In [ ]:
# Function to map positions in a list
def map_positions(position_list):
    return [positions_map[pos] for pos in position_list]

# Apply the mapping function to the 'position' column
df.main_position = df.main_position.apply(map_positions)

# peek
df.main_position.head()

In [ ]:
# Returns "striker" if it's in the list, otherwise returns the first position.
def select_main_position(positions):
    if positions == ["midfielder", "striker"]:
        return "striker"
    return positions[0]

# Applies the select_main_position function to the 'main_position' column in the DataFrame.
df.main_position = df.main_position.apply(select_main_position)

In [ ]:
# peek
df.main_position.head(20)

###  changing the types of the features

#### defining regex

In [ ]:
def extract_numbers(input_string):
    # Use regular expression to extract numbers
    numbers = re.findall(r'\d+', input_string)
    
    # Join the numbers into a single string or convert to a list depending on your needs
    result = ''.join(numbers)  # If you want a single string
    # result = [int(num) for num in numbers]  # If you want a list of integers
    
    return result

# def extract_date(input_string):
#     # Use regular expression to extract the date
#     date_match = re.search(r'\b\d{1,2}/\d{1,2}/\d{4}\b', input_string)
#
#     if date_match:
#         return date_match.group()
#     else:
#         return None

def extract_amount(input_string):
    # Use regular expression to extract numeric values with optional K or M suffix
    match = re.search(r'(?i)([0-9,.]+)([km]?)', input_string)
    
    if match:
        value_str, suffix = match.groups()
        value = float(value_str.replace(',', '.'))

        if suffix.lower() == 'k':
            value *= 1e3
        elif suffix.lower() == 'm':
            value *= 1e6

        return value
    else:
        return None

#### converting columntypes

In [ ]:
# applying regex to features with 'dirty' numbers

#df.dob = df.dob.apply(extract_date)
df.height = df.height.apply(extract_numbers)
df.weight = df.weight.apply(extract_numbers)
df.wage = df.wage.apply(extract_numbers)
df['last trans. fee'] = df['last trans. fee'].apply(extract_amount)
df.value = df.value.apply(extract_amount)

In [ ]:
numerical_columns = ['age', 'height', 'weight', 'wage', 'last trans. fee', 'value',
                      'agg', 'jum', 'pun', 'vis', 'l th', 'lon', 'otb', 'tck', 'tec', 'tea',
                      'cmp', 'fre', 'ref', 'pos', 'pen', 'pas', 'fla', 'ant', 'cro', 'mar', 'ldr', 'cor', 'cnt', 'det',
                      'dec', 'hea', 'fir', 'com', 'acc', 'pac', 'aer', 'str', 'thr', 'han', 'ecc', 'dri', 'bal', 'kic',
                      'sta', 'agi', 'wor', 'bra', 'cmd', 'fin', '1v1', 'tro']

In [ ]:
# Convert numerical columns to float32, replacing non-convertible values with NaN
df[numerical_columns] = df[numerical_columns].apply(pd.to_numeric, errors='coerce').astype('float32')

# Convert 'dob' column to datetime
# df['dob'] = pd.to_datetime(df['dob'], errors='coerce')

In [ ]:
# check
df.info()

### onehotencode main position

In [ ]:
df.head()

In [ ]:
df = pd.get_dummies(df, columns=['main_position'], prefix="", prefix_sep="")

In [ ]:
# peek
df.sample(5)

### quantify division

In [ ]:
# peek
df.division.sample(5)

In [ ]:
df.division.nunique()

#### reduce number of unique values

In [ ]:
thresholds = range(1, 101)

# Calculate value counts once outside the loop
value_counts = df['division'].value_counts()

# Use vectorized operations within the loop
unique_values_counts = [
    len(df.loc[~df['division'].isin(value_counts[value_counts < threshold].index), 'division'].unique())
    for threshold in thresholds
]

# Plot the results
plt.figure(figsize=(10, 6))
plt.plot(thresholds, unique_values_counts, linestyle='-', color='b')
plt.title('Number of Unique Values vs. Threshold')
plt.xlabel('Threshold')
plt.ylabel('Number of Unique Values')
plt.grid(True)
plt.show()

In [ ]:
# Identify less frequent values
threshold = 50  # Adjust as needed
value_counts = df['division'].value_counts()
rare_values = value_counts[value_counts < threshold].index

# Replace less frequent values with a common category
df['division'] = df['division'].replace(rare_values, 'Other')
df['division'] = df['division'].replace('', 'Other')
df['division'] = df['division'].replace('-', 'Other')

In [ ]:
df.division.value_counts().get('Other', 0)

In [ ]:
df.division.unique()

##### league ratings, country abbreviations and division abbreviations

In [ ]:
divisions_abbreviations = {
    'English Premier Division': 'ENG1',
    'Sky Bet Championship': 'ENG2',
    'Scottish Premiership': 'SCO1',
    'Turkish Super League': 'TUR1',
    'Russian Premier League': 'RUS1',
    'Ukrainian Premier League': 'UKR1',
    'Croatian First League': 'CRO1',
    '3F Superliga': 'DEN1',
    'Serbian SuperLeague': 'SRB1',
    'Greek Super League 1': 'GRE1',
    'Czech First Division': 'CZE1',
    'Sky Bet League One': 'ENG3',
    'Swedish Premier Division': 'SWE1',
    'Russian First Division': 'RUS2',
    'Bulgarian First League': 'BUL1',
    'Slovenian First League': 'SVN1',
    'Romanian First League': 'ROU1',
    'Israeli Premier League': 'ISR1',
    'Hungarian Division I': 'HUN1',
    'Sky Bet League Two': 'ENG4',
    'Norwegian Premier Division': 'NOR1',
    'Turkish 1. League': 'TUR2',
    'PKO Bank Polski Ekstraklasa': 'POL1',
    'Scottish Championship': 'SCO2',
    'Cypriot First Division': 'CYP1',
    'Norwegian First Division': 'NOR2',
    'Croatian Second League': 'CRO2',
    'Kazakhstan Premier League': 'KAZ1',
    'Other': 'OTH1',
    'Finnish Premier League': 'FIN1',
    'Greek Super League 2': 'GRE2',
    'Swedish First Division Elite': 'SWE2',
    'Ukrainian First League': 'UKR2',
    'Turkish 2. League White Group': 'TUR3',
    '1. Division': 'BRA1',
    'Bosnian Premier League': 'BIH1',
    'Czech Third Division CFL A': 'CZE3',
    'Irish Premier Division': 'IRL1',
    'Ukrainian Second League - Group B': 'UKR3',
    'Finnish Second Division Group B': 'FIN2',
    'Serbian First League': 'SRB2',
    'Turkish 2. League Red Group': 'TUR4',
    'Maltese Premier League': 'MLT1',
    '2. Division': 'NOR3',
    'Slovak First Division': 'SVK1',
    'Polish First Division': 'POL2',
    'Hungarian Division II': 'HUN2',
    'Serbian Second League Belgrade': 'SRB3',
    'Russian Lower Division': 'RUS3',
    'Slovenian Second League': 'SVN2',
    'Romanian Third League Group 4': 'ROU3',
    'Vanarama National League': 'ENG5',
    'Belarusian Highest League': 'BLR1',
    'Czech Second Division': 'CZE2',
    'Ukrainian Second League - Group A': 'UKR4',
    'Irish First Division': 'IRL2',
    'Slovak Second Division': 'SVK2',
    'Russian Second Division - Group 1': 'RUS4',
    'Finnish First Division': 'FIN3',
    'Hungarian Division III - West': 'HUN3',
    'Norwegian Third Division Group 4': 'NOR4',
    'Armenian High League': 'ARM1',
    'Swedish First Division North': 'SWE3',
    'Hungarian Division III - Centre': 'HUN4',
    'Russian Second Division - Group 4': 'RUS5',
    'Russian Second Division - Group 3': 'RUS6',
    'Russian Second Division - Group 2': 'RUS7',
    'Norwegian Second Division Group 2': 'NOR5',
    'Hungarian Division III - East': 'HUN5',
    'Israeli National League': 'ISR2',
    'Serbian Zone League': 'SRB4',
    'Polish Second Division': 'POL3',
    'Icelandic Premier Division': 'ISL1',
    'Romanian Second League': 'ROU4',
    'Ukrainian Lower Division': 'UKR5',
    'Scottish League 1': 'SCO3',
    'Turkish 3. League Group 3': 'TUR5',
    'Vanarama National League South': 'ENG6',
    'Swedish Second Division West G√∂taland': 'SWE4',
    'Danske Bank Premiership': 'NIR1',
    'Croatian Third League North': 'CRO3',
    'Croatian Third League South': 'CRO4',
    'Romanian Third League Group 6': 'ROU5',
    'Swedish First Division South': 'SWE5',
    'Israeli A League South Division': 'ISR3',
    'Czech Third Division CFL B': 'CZE4',
    'Czech Third Division MSFL': 'CZE5',
    'Vanarama National League North': 'ENG7',
    'Finnish Lower Division': 'FIN4',
    'Turkish 3. League Group 1': 'TUR6',
    'Norwegian Third Division Group 3': 'NOR6',
    'Icelandic First Division': 'ISL2',
    'Romanian Third League Group 2': 'ROU6',
    'Romanian Third League Group 5': 'ROU7',
    'Croatian Third League East': 'CRO5',
    'Turkish 3. League Group 2': 'TUR7',
    'Czech Fourth Division D': 'CZE6',
    'Romanian Third League Group 3': 'ROU8',
    'Norwegian Third Division Group 1': 'NOR7',
    'Serbian Second League Vojvodina': 'SRB5',
    'Swedish Second Division South Svealand': 'SWE6',
    'Romanian Third League Group 7': 'ROU9',
    'Greek Football League South': 'GRE3',
    'Finnish Third Division': 'FIN5',
    'Czech Fourth Division A': 'CZE7',
    'Czech Lower Division': 'CZE8',
    'Czech Fourth Division F': 'CZE9',
    'Norwegian Second Division Group 1': 'NOR8',
    'Polish Third Division Group 1': 'POL4',
    'Finnish Second Division Group A': 'FIN6',
    'Croatian Third League Central': 'CRO6',
    'Norwegian Third Division Group 2': 'NOR9',
    'Finnish Second Division Group C': 'FIN7',
    'Israeli A League North Division': 'ISR4',
    'Turkish 3. League Group 4': 'TUR8',
    'Slovenian Third League East': 'SVN3',
    'Norwegian Third Division Group 6': 'NOR10',
    'Romanian Third League Group 10': 'ROU10',
    'Bulgarian Second League': 'BUL2',
    'Belarusian First League': 'BLR2',
    'Hungarian Lower Division': 'HUN6',
    'Polish Fourth Division': 'POL5',
    'Romanian Third League Group 8': 'ROU11',
    'Greek Football League North': 'GRE4',
    'Romanian Third League Group 9': 'ROU12',
    'Swedish Second Division North G√∂taland': 'SWE7',
    'Israeli B League South A Division': 'ISR5',
    'JD Cymru Premier': 'WAL1',
    'Swedish Second Division East G√∂taland': 'SWE8',
    'Romanian Lower League': 'ROU13',
    'Romanian Third League Group 1': 'ROU14',
    'Czech Fourth Division C': 'CZE10',
    'Swedish Third Division Middle G√∂taland': 'SWE9',
    'Swedish Second Division Norrland': 'SWE10',
    'Polish Third Division Group 4': 'POL6',
    'Scottish League 2': 'SCO4',
    'Serbian Second League East': 'SRB6',
    'Czech Fourth Division B': 'CZE11',
    'Icelandic U19 Division B': 'ISL3',
    'Greek Regional Division Group 6': 'GRE5',
    'JD Cymru North': 'WAL2',
    'Slovenian Third League West': 'SVN4',
    'Serbian Second League West': 'SRB7',
    'Polish Third Division Group 3': 'POL7',
    'Irish Leinster Senior League Premier Division': 'IRL3',
    'Scottish Lowland League': 'SCO5',
    'Swedish Second Division North Svealand': 'SWE11',
    'Icelandic Second Division': 'ISL4',
    'Polish Third Division Group 2': 'POL8',
    'Slovenian Lower League': 'SVN5',
    "Bulgarian 'A' Regional Groups": 'BUL3',
    'Israeli B League South B Division': 'ISR6',
    'Bluefin Sport Championship': 'NIR2',
    'Croatian Third League West': 'CRO7',
    'Icelandic U19 Division A': 'ISL5',
    'Greek Regional Division Group 10': 'GRE6',
    'West of Scotland Premier Division': 'SCO6',
    'Greek Regional Division Group 9': 'GRE7',
    'Greek Regional Division Group 4': 'GRE8',
    'Icelandic Third Division': 'ISL6',
    'Greek Regional Division Group 1': 'GRE9',
    'Greek Regional Division Group 5': 'GRE10',
    'Greek Regional Division Group 2': 'GRE11',
    'Greek Regional Division Group 7': 'GRE12',
    'Highland Football League': 'SCO7',
    'Greek Regional Division Group 3': 'GRE13',
    'Greek Regional Division Group 8': 'GRE14',
    'Swedish Third Division West Svealand': 'SWE12',
    'Slovak Lower Division': 'SVK3',
    'East of Scotland Premier Division': 'SCO8',
    'Northern Amateur Football League Premier Division': 'NIR3',
    'Belarusian Second League': 'BLR4',
    'Bulgarian Third League North-East': 'BUL4',
    'Israeli B League North A Division': 'ISR7',
    'Bulgarian Third League North-West': 'BUL5',
    'Bulgarian Third League South-East': 'BUL6',
    'JD Cymru South': 'WAL3',
    'North Caledonian League': 'SCO9',
    'Swedish Third Division Northeast G√∂taland': 'SWE13',
    'Israeli B League North B Division': 'ISR8',
    'Bulgarian Third League South-West': 'BUL7',
    'Swedish Third Division South Svealand': 'SWE14',
    'Bluefin Sport Premier Intermediate League': 'NIR4',
    'Swedish Third Division North Svealand': 'SWE15',
    'Norwegian Lower Division': 'NOR11',
    'Icelandic Lower Division': 'ISL7',
    'Northern Irish Ballymena Premier Division': 'NIR5',
    'Croatian Regional League - Split (17)': 'CRO8',
    'Greek Amateur First Division - Athens Group A': 'GRE15',
    'Ligue 1 Uber Eats': 'FRA1',
    'Bundesliga': 'GER1',
    'Spanish First Division': 'ESP1',
    'Italian Serie A': 'ITA1',
    'Eredivisie': 'NED1',
    'Portuguese Premier League': 'POR1',
    'Spanish Second Division': 'ESP2',
    'Belgian Pro League A': 'BEL1',
    'Swiss Super League': 'SUI1',
    'Belgian Pro League B': 'BEL2',
    'Austrian Premier Division': 'AUT1',
    'Swiss Challenge League': 'SUI2',
    'Italian Serie B': 'ITA2',
    'Spanish Third Division Group 6': 'ESP3',
    'Spanish Second Division B2': 'ESP2',
    'Bundesliga 2': 'GER2',
    'Spanish Second Division B3': 'ESP2',
    'Ligue 2 BKT': 'FRA2',
    '3. Liga': 'GER3',
    'French National 2 - C': 'FRA4',
    'German Regional Division Southwest': 'GER4',
    'Spanish Second Division B4': 'ESP2',
    'Italian Serie C/C': 'ITA3',
    'German Regional Division West': 'GER4',
    'Spanish Second Division B5': 'ESP2',
    'Austrian First Division': 'AUT1',
    'Keuken Kampioen Divisie': 'NED2',
    'Portuguese Second League': 'POR2',
    'French National 3 - Paris Ile de France': 'FRA5',
    'German Regional Division Northeast': 'GER4',
    'French National 3 - Corse - M√©diterran√©e': 'FRA5',
    'Italian Serie C/B': 'ITA3',
    'French National 3 - Bourgogne Franche Comt√©': 'FRA5',
    'Spanish Second Division B1': 'ESP2',
    'Spanish Third Division Group 4': 'ESP3',
    'Portugal Championship - Group G': 'POR4',
    'Spanish Third Division Group 7': 'ESP3',
    'French National 3 - Auvergne Rh√¥ne Alpes': 'FRA5',
    'French National': 'FRA3',
    'French National 3 - Nouvelle Aquitaine': 'FRA5',
    'Portugal Championship - Group A': 'POR4',
    'Italian Serie C/A': 'ITA3',
    'Portugal Championship - Group C': 'POR4',
    'Portugal Championship - Group B': 'POR4',
    'Spanish Third Division Group 8': 'ESP3',
    'French National 2 - B': 'FRA4',
    'French National 3 - Hauts de France': 'FRA5',
    'Spanish Third Division Group 2': 'ESP3',
    'Austrian Regional League Salzburg': 'AUT4',
    'German Regional Division North': 'GER4',
    'Luxembourg National Division': 'LUX1',
    'Spanish Third Division Group 10': 'ESP3',
    'Belgian First Amateur Division': 'BEL3',
    'French National 2 - A': 'FRA4',
    'French National 3 - Occitanie': 'FRA5',
    'Swiss Promotion League': 'SUI2',
    'French National 3 - Bretagne': 'FRA5',
    'Spanish Third Division Group 1': 'ESP3',
    'French National 2 - D': 'FRA4',
    'French National 3 - Grand Est': 'FRA5',
    'Austrian Regional League East': 'AUT3',
    'Spanish Third Division Group 17': 'ESP3',
    'Portugal Championship - Group H': 'POR4',
    'Austrian Regional League Central': 'AUT3',
    'Spanish Third Division Group 13': 'ESP3',
    'Swiss First League Group 3': 'SUI3',
    'Spanish Third Division Group 9': 'ESP3',
    'Spanish Third Division Group 18': 'ESP3',
    'Portugal Championship - Group E': 'POR4',
    'German Div. Bavaria South': 'GER5',
    'Italian Serie D Grp. C': 'ITA4',
    'Italian Serie D Grp. B': 'ITA4',
    'Belgian Third Amateur Division A (Wal)': 'BEL4',
    'Portugal Championship - Group F': 'POR4',
    'Spanish Third Division Group 11': 'ESP3',
    'Austrian Lower Austria League': 'AUT4',
    'German Regional Division Bavaria': 'GER4',
    'Austrian Regional League Tyrol': 'AUT4',
    'German Lower Division': 'GER5',
    'Portuguese Algarve First Division': 'POR5',
    'Swiss First League Group 1': 'SUI3',
    'Swiss First League Group 2': 'SUI3',
    'Spanish Third Division Group 16': 'ESP3',
    'Spanish Third Division Group 5': 'ESP3',
    'Belgian Second Amateur Division C': 'BEL4',
    'French Regional 1 - Auvergne Rh√¥ne Alpes - Group C': 'FRA6',
    'Swiss Second League Interregio Gr 1': 'SUI4',
    'Austrian Tyrol League': 'AUT4',
    'Portugal Championship - Group D': 'POR4',
    'Dutch Tweede Divisie': 'NED3',
    'French National 3 - Normandie': 'FRA5',
    'French National 3 - Centre Val de Loire': 'FRA5',
    'German Div. Baden-W√ºrttemberg': 'GER5',
    'Spanish Third Division Group 12': 'ESP3',
    'Italian Serie D Grp. E': 'ITA4',
    'French Regional Divisions': 'FRA6',
    'Spanish Third Division Group 3': 'ESP3',
    'Belgian Second Amateur Division B': 'BEL4',
    'Italian Serie D Grp. H': 'ITA4',
    'Italian Serie D Grp. A': 'ITA4',
    'Belgian Third Amateur Division B (Fla)': 'BEL4',
    'Italian Serie D Grp. G': 'ITA4',
    'Italian Serie D Grp. F': 'ITA4',
    'Swiss Second League Interregio Gr 4': 'SUI4',
    'Italian Serie D Grp. I': 'ITA4',
    'Spanish Third Division Group 14': 'ESP3',
    'Italian Serie D Grp. D': 'ITA4',
    'French National 3 - Pays de la Loire': 'FRA5',
    'Austrian Vienna League': 'AUT5',
    'Austrian Eliteleague Vorarlberg': 'AUT5',
    'Swiss Second League Interregio Gr 2': 'SUI4',
    'Portuguese Lower Regional Divisions': 'POR5',
    'Antwerp Provincial Division': 'BEL5',
    'Belgian Second Amateur Division A': 'BEL4',
    'Swiss Second League Interregio Gr 6': 'SUI4',
    'Portuguese Porto First Division Serie 1': 'POR5',
    'Limburg Provincial Division': 'BEL5',
    'Swiss Second League Interregio Gr 5': 'SUI4',
    'West-Flanders Provincial Division': 'BEL5',
    'Swiss Under 18 Elite': 'SUI6',
    'Belgian Third Amateur Division A (Fla)': 'BEL4',
    'Swiss Second League Interregio Gr 3': 'SUI4',
    'Belgian Third Amateur Division B (Wal)': 'BEL4',
    'Swiss Under 18 (17)': 'SUI6',
    'Swiss Lower Division': 'SUI7',
    'East-Flanders Provincial Division': 'BEL5',
    'Portuguese Lisbon First Division': 'POR5',
    'Portuguese Set√∫bal First Division': 'POR5',
    'Portuguese Porto First Division Serie 2': 'POR5',
    'Dutch Derde Divisie Zaterdag': 'NED4',
    'Brazilian National First Division': 'BRA1',
    'Argentine Premier Division': 'ARG1',
    'Colombian First Division': 'COL1',
    'Brazilian National Second Division': 'BRA2',
    'Argentine Second Division': 'ARG2',
    'Ecuadorian LigaPro Serie A': 'ECU1',
    'Chilean First Division': 'CHI1',
    'Uruguayan First Division': 'URU1',
    'Argentine Torneo Federal A': 'ARG3',
    'Paraguay First Division Primera Divisi√≥n': 'PAR1',
    'Chilean First Division B': 'CHI2',
    'Argentine Metropolitan B Zone': 'ARG4',
    'Argentine Metropolitan C Zone': 'ARG4',
    'Brazilian National Fourth Division': 'BRA4',
    'Argentine Torneo Federal C': 'ARG4',
    'Argentine Torneo Federal B': 'ARG4',
    'Brazilian National Third Division': 'BRA3',
    'Brazilian National Lower Division': 'BRA5',
    'Bolivian Premier Division': 'BOL1',
    'Argentine Metropolitan D Zone': 'ARG4',
    'Peruvian First Division': 'PER1',
    'Colombian Second Division': 'COL2',
    'Chilean Second Division': 'CHI3',
    'Uruguayan Second Professional Division': 'URU2',
    'Peruvian Second Division': 'PER2',
    'Peruvian Copa Peru': 'PER3',
    'Chilean Third Division A': 'CHI4',
    'Chilean South Group Third Division B': 'CHI4',
    'Uruguayan First Amateur Division': 'URU3',
    'Uruguayan Rocha Department': 'URU4',
    'Chilean North Group Third Division B': 'CHI4',
    'Chilean Centre Group Third Division B': 'CHI4',
    'Chinese Super League': 'CHN1',
    'Saudi Professional League': 'KSA1',
    'UAE Professional League': 'UAE1',
    'Qatari Stars League': 'QAT1',
    'Chinese National First Division': 'CHN2',
    'Chinese National Second Division Northern Group': 'CHN3',
    'Hana 1Q K LEAGUE 2': 'KOR2',
    'Iraqi Premier League': 'IRQ1',
    'A-League': 'AUS1',
    'Saudi First Division': 'KSA2',
    'Hana 1Q K LEAGUE 1': 'KOR1',
    'Uzbekistan Superleague': 'UZB1',
    'Kuwaiti Premier League': 'KUW1',
    'Syrian Premier League': 'SYR1',
    'Thai League': 'THA1',
    'Iranian Professional League': 'IRN1',
    'National Premier Leagues - Queensland': 'AUS2',
    'Football Queensland Premier League': 'AUS3',
    'National Premier Leagues - NSW': 'AUS4',
    'National Premier Leagues - Victoria': 'AUS5',
    'Singaporean Premier League': 'SGP1',
    'Malaysian Super League': 'MAS1',
    'National Premier Leagues - Western Australia': 'AUS6',
    'Hong Kong Premier League': 'HKG1',
    'National Premier Leagues - Northern NSW': 'AUS7',
    'Korean K3 League': 'KOR3',
    'Bahraini Premier League': 'BHR1',
    'Malaysian Premier League': 'MAS2',
    'Indian National Football League': 'IND1',
    'Indonesian League One': 'IDN1',
    'National Premier Leagues - Victoria 2': 'AUS8',
    'National Premier Leagues - NSW 2': 'AUS9',
    'Indonesian League Two': 'IDN2',
    'National Premier Leagues - South Australia': 'AUS10',
    'National Premier Leagues - Victoria 3': 'AUS11',
    'North Korean Premier Football League': 'PRK1',
    'Singaporean Football League Division Two': 'SGP2',
    'National Premier Leagues - ACT': 'AUS12',
    'Bruneian Super League': 'BRN1',
    'Indian Lower Division': 'IND2',
    'Malaysian Division Three League Group A': 'MAS3',
    'South Australia - State League 2': 'AUS13',
    'Singaporean Football League Division One': 'SGP3',
    'South Australia - State League 1': 'AUS14',
    'Malaysian Division Three League Group B': 'MAS3',
    'Western Australia State League Division 1': 'AUS15',
    'Malaysian Lower Division': 'MAS4',
    'Victorian State League 1 South-East': 'AUS16',
    'Western Australia State League Division 2': 'AUS17',
    'Victorian State League 2 North-West': 'AUS18',
    'Brisbane Premier League': 'AUS19',
    'National Premier Leagues - ACT 2': 'AUS20',
    'NNSW Northern League One': 'AUS21',
    'Victorian State League 1 North-West': 'AUS22',
    'Bruneian Premier League': 'BRN1',
    'Bruneian Lower Division': 'BRN2',
    'Victorian State League 2 South-East': 'AUS23',
    'National Premier Leagues - Tasmania': 'AUS24',
    'Major League Soccer': 'USA1',
    'Egyptian Premier League': 'EGY1',
    'Mexican First Division': 'MEX1',
    'Tunisian League 1': 'TUN1',
    'USSL Championship Western Conference': 'USA2',
    'Moroccan Premier Division': 'MAR1',
    'Lower Leagues': 'UNK1',
    'USSL Championship Eastern Conference': 'USA2',
    'United States Soccer Leagues Division One': 'USA3',
    'Mexican Expansion League': 'MEX2',
    'South African Premier Soccer League': 'RSA1',
    'Canadian Premier League': 'CAN1',
    'National Independent Soccer Association': 'USA3',
    'USSL D2 - Great Lakes Division': 'USA4',
    'MLS Next - Mid-America Division': 'USA3',
    'Angolan Championship': 'ANG1',
    'USSL D2 - Mountain Division': 'USA4',
    'South African National First Division': 'RSA2',
    'USSL D2 - Southeast Division': 'USA4',
    'Mexican Premier Division Serie A Group II': 'MEX3',
    'Solomon Islands S-League': 'SOL1',
    'Papua New Guinean National Soccer League': 'PNG1',
    'Fijian Premier League': 'FIJ1',
    'Premi√®re Ligue de soccer du Qu√©bec': 'CAN3',
    'SAFA Gauteng Division 2': 'RSA3',
    'USSL D2 - Mid Atlantic Division': 'USA4',
    'Championnat Super Ligue': 'NCL1',
    'Vanuatuan Port Vila Premier Division': 'VAN1',
    'Tahitian First Division': 'TAH1',
    'SAFA KwaZulu Natal Division 2': 'RSA3',
    'SAFA Western Cape Division 2': 'RSA3',
    'Fijian Lower Division': 'FIJ2',
    'New Zealand Premiership': 'NZL1',
    'Mexican Premier Division Serie A Group I': 'MEX3',
    'Bermudan Premier Division': 'BER1',
    'New Zealand Central Premier League': 'NZL2',
    'New Zealand NRFL Premier Division': 'NZL2',
    'New Zealand NRFL Division One': 'NZL3',
    'New Zealand Mainland Premier League': 'NZL3',
    'Samoan Premier League': 'SAM1',
    'Cook Islands Round Cup': 'COK1',
    'MLS Next - Southeast Division': 'USA3',
    'American Samoan Senior League Division One': 'ASA1',
    'League1 Ontario': 'CAN3',
    'MLS Next - Northwest Division': 'USA4',
    'New Zealand NRFL Division Two': 'NZL4',
    'USSL D2 - Southwest Division': 'USA4',
    'USSL D2 - Northeast Division': 'USA4',
    'USSL D2 - Heartland Division': 'USA4',
    'USSL D2 - Mid South Division': 'USA4',
    'USSL D2 - Northwest Division': 'USA4',
    'USSL D2 - South Atlantic Division': 'USA4',
    'MLS Next - Northeast Division': 'USA3',
    'MLS Next - Atlantic Division': 'USA3',
    'MLS Next - Frontier Division': 'USA3',
    'MLS Next - Southwest Division': 'USA3'}

In [ ]:
full_league_ratings = [
    ('England', 93.8), ('Spain', 90.8), ('Germany', 90.3), ('Italy', 89.5), ('Brazil', 86.2), ('France', 85.1),
    ('Portugal', 84.4), ('Argentina', 80.8), ('Turkey', 80.8), ('Greece', 80.7), ('Mexico', 80.0), ('Russia', 79.8),
    ('Czech Republic', 78.4), ('Netherlands', 78.4), ('Colombia', 78.1), ('Switzerland', 77.4), ('Spain', 77.3),
    ('Germany', 77.1), ('Denmark', 77.1), ('Paraguay', 76.9), ('Belgium', 76.8), ('Croatia', 76.8), ('Ecuador', 76.6),
    ('Brazil', 75.5), ('England', 75.4), ('Austria', 75.3), ('Italy', 74.8), ('Sweden', 74.2), ('Israel', 73.9),
    ('Cyprus', 73.7), ('Poland', 73.5), ('Romania', 73.4), ('Uruguay', 72.7), ('Mexico', 72.2), ('Norway', 72.1),
    ('France', 71.7), ('South Korea', 71.6), ('Portugal', 71.6), ('Chile', 71.4), ('Argentina', 71.4),
    ('Slovakia', 71.0), ('Iran', 71.0), ('Serbia', 70.9), ('Brazil', 70.9), ('Costa Rica', 70.8), ('Hungary', 70.8),
    ('Turkey', 70.2), ('Bosnia and Herzegovina', 70.1), ('Germany', 70.0), ('Bulgaria', 69.8), ('Georgia', 69.8),
    ('Ukraine', 69.5), ('Colombia', 69.4), ('Peru', 69.4), ('USA', 69.3), ('Australia', 69.1), ('Spain', 68.7),
    ('Belarus', 68.6), ('Japan', 68.5), ('Scotland', 68.4), ('China PR', 67.5), ('Argentina', 67.5), ('Brazil', 67.2),
    ('United Arab Emirates', 67.2), ('Azerbaijan', 66.8), ('Saudi Arabia', 66.7), ('Venezuela', 66.6), ('England', 66.5),
    ('Ecuador', 66.3), ('Italy', 66.3), ('Paraguay', 66.2), ('Australia', 66.1), ('Switzerland', 66.0), ('Greece', 65.9),
    ('Guatemala', 65.5), ('France', 65.5), ('Bolivia', 65.4), ('Kazakhstan', 65.2), ('Slovenia', 65.0), ('Albania', 64.9),
    ('Iceland', 64.8), ('Russia', 64.8), ('Morocco', 64.8), ('Macedonia', 64.7), ('Poland', 64.7), ('Mexico', 64.7),
    ('Chile', 64.4), ('Portugal', 64.2), ('Finland', 64.2), ('Denmark', 63.6), ('Honduras', 63.5), ('Uruguay', 63.3),
    ('Algeria', 63.2), ('Czech Republic', 63.2), ('Tunisia', 62.9), ('Israel', 62.7), ('Turkey', 62.6), ('Qatar', 62.6),
    ('Panama', 62.5), ('Republic of Ireland', 62.4), ('Argentina', 62.3), ('Germany', 62.1), ('Spain', 61.4),
    ('Romania', 61.2), ('South Korea', 61.1), ('Montenegro', 61.1), ('Iran', 60.8), ('Peru', 60.7),
    ('Netherlands', 60.6), ('Sweden', 60.5), ('Greece', 60.3), ('Croatia', 60.0), ('Moldova', 59.7),
    ('Northern Ireland', 59.6), ('Egypt', 59.5), ('Nigeria', 59.5), ('Argentina', 59.3), ('Iraq', 59.2), ('Belgium', 59.1),
    ('Uzbekistan', 59.0), ('Serbia', 59.0), ('Hungary', 58.9), ('South Africa', 58.9), ('England', 58.8),
    ('Argentina', 58.8), ('Italy', 58.7), ('Costa Rica', 58.6), ('USA', 58.4), ('Lithuania', 58.4), ('Kuwait', 58.3),
    ('France', 58.0), ('Norway', 57.9), ('Venezuela', 57.4), ('Chile', 57.2), ('El Salvador', 57.2), ('Bahrain', 57.1),
    ('Slovakia', 57.1), ('Thailand', 56.8), ('Japan', 56.6), ("Ivory Coast", 56.5), ('Ghana', 56.4), ('Poland', 56.1),
    ('Guatemala', 55.9), ('Austria', 55.9), ('Bosnia and Herzegovina', 55.8), ('Georgia', 55.5), ('Cyprus', 55.1),
    ('Israel', 55.1), ('Morocco', 55.1), ('Latvia', 54.9), ('Panama', 54.9), ('Kosovo', 54.9), ('Senegal', 54.9),
    ('Jordan', 54.6), ('Oman', 54.4), ('Armenia', 54.3), ('Uruguay', 54.2), ('Algeria', 54.1), ('Turkey', 53.8),
    ('Jamaica', 53.8), ('Greece', 53.7), ('Syria', 53.5), ('Wales', 53.5), ('Denmark', 53.5), ('Albania', 53.1),
    ('Cameroon', 52.7), ('Serbia', 52.6), ('South Korea', 52.6), ('Congo DR', 52.6), ('China PR', 52.4),
    ('Zambia', 52.4), ('Bulgaria', 52.4), ('Angola', 52.3), ('Faroe Islands', 52.2), ('Scotland', 52.0), ('Chile', 52.0),
    ('Tunisia', 52.0), ('Switzerland', 51.9), ('France', 51.7), ('Spain', 51.7), ('Congo', 51.7), ('Montenegro', 51.6),
    ('Qatar', 51.3), ('Czech Republic', 51.1), ('Sweden', 51.0), ('Saudi Arabia', 50.9), ('Gabon', 50.8), ('England', 50.8),
    ('Togo', 50.6), ('Kenya', 50.6), ('Macedonia', 50.3), ('Gambia', 50.3), ('Russia', 50.1),
    ('United Arab Emirates', 50.1), ('Croatia', 50.0), ('Kazakhstan', 49.9), ('Belarus', 49.8), ('Mali', 49.6),
    ('Libya', 49.6), ('Finland', 49.1), ('Slovenia', 48.7), ('Burkina Faso', 48.5), ('Slovakia', 48.5),
    ('Romania', 48.4), ('Ethiopia', 48.4), ('Azerbaijan', 48.2), ('Malta', 48.2), ('Nicaragua', 48.2),
    ('Belgium', 48.2), ('Uzbekistan', 48.1), ('Ukraine', 48.0), ('Lebanon', 47.8), ('Tanzania', 47.8),
    ('Republic of Ireland', 47.8), ('Netherlands', 47.8), ('South Africa', 47.7), ('Iceland', 47.2),
    ('Rwanda', 47.2), ('Zimbabwe', 47.1), ('Poland', 47.1), ('Luxembourg', 47.1), ('Uganda', 46.9), ('Sudan', 46.8),
    ('Guinea', 46.6), ('Japan', 46.0), ('Bolivia', 45.9), ('Mozambique', 45.9), ('USA', 45.9), ('Israel', 45.2),
    ('Hungary', 45.1), ('Palestine', 44.8), ('Swaziland', 44.8), ('Norway', 44.4), ('Japan', 44.0), ('Gibraltar', 43.9),
    ('Cyprus', 43.8), ('Scotland', 43.7), ('India', 43.5), ('Thailand', 43.4), ('Georgia', 43.3), ('New Zealand', 43.1),
    ('Albania', 42.9), ('Sierra Leone', 42.4), ('Haiti', 42.2), ('Estonia', 42.0), ('Switzerland', 41.8),
    ('Bulgaria', 41.5), ('Bahrain', 41.3), ('Trinidad and Tobago', 41.1), ('Vietnam', 40.8)
]

In [ ]:
# Sort the list alphabetically by country names
sorted_league_ratings = sorted(full_league_ratings, key=lambda x: x[0])

# Display the sorted list
for country, rating in sorted_league_ratings:
    print(f'{country}: {rating}')

In [ ]:
# Abbreviations for countries
country_abbreviations = {
    'Germany': 'GER', 'Paraguay': 'PRY', 'Angola': 'AGO', 'Denmark': 'DNK',
    'Norway': 'NOR', 'Switzerland': 'CHE', 'Scotland': 'SCO', 'Wales': 'WAL',
    'Saudi Arabia': 'SAU', 'Nigeria': 'NGA', 'Vanuatu': 'VUT', 'Iran': 'IRN',
    'Congo DR': 'COD', 'Venezuela': 'VEN', 'Mali': 'MLI', 'Italy': 'ITA',
    'Finland': 'FIN', 'Peru': 'PER', 'Ivory Coast': 'CIV', 'Puerto Rico': 'PRI',
    'Portugal': 'PRT', 'Ghana': 'GHA', 'Romania': 'ROU', 'Costa Rica': 'CRC',
    'Colombia': 'COL', 'Turkey': 'TUR', 'Australia': 'AUS', 'Austria': 'AUT',
    'Netherlands': 'NLD', 'Cyprus': 'CYP', 'Greece': 'GRC', 'England': 'ENG',
    'Sweden': 'SWE', 'El Salvador': 'SLV', 'Turkmenistan': 'TKM', 'Cameroon': 'CMR',
    'Algeria': 'DZA', 'Thailand': 'THA', 'India': 'IND', 'France': 'FRA',
    'South Africa': 'ZAF', 'Estonia': 'EST', 'United Arab Emirates': 'ARE',
    'Macedonia': 'MKD', 'Bulgaria': 'BGR', 'Niger': 'NER', 'Kazakhstan': 'KAZ',
    'Lebanon': 'LBN', 'Qatar': 'QAT', 'Sudan': 'SDN', 'Jordan': 'JOR', 'Libya': 'LBY',
    'Egypt': 'EGY', 'Kuwait': 'KWT', 'Iraq': 'IRQ', 'Russia': 'RUS', 'Uruguay': 'URY',
    'Japan': 'JPN', 'Argentina': 'ARG', 'Panama': 'PAN', 'Spain': 'ESP',
    'Guyana': 'GUY', 'Slovenia': 'SVN', 'Bolivia': 'BOL', 'Mexico': 'MEX',
    'Brazil': 'BRA', 'Uzbekistan': 'UZB', 'Guatemala': 'GTM', 'Armenia': 'ARM',
    'Azerbaijan': 'AZE', 'Haiti': 'HTI', 'Northern Ireland': 'NIR', 'Indonesia': 'IDN',
    'Singapore': 'SGP', 'Jamaica': 'JAM', 'Nicaragua': 'NIC', 'Tunisia': 'TUN',
    'New Caledonia': 'NCL', 'Morocco': 'MAR', 'Trinidad and Tobago': 'TTO',
    'Republic of Ireland': 'IRL', 'USA': 'USA', 'Honduras': 'HND', 'Ecuador': 'ECU',
    'New Zealand': 'NZL', 'Chile': 'CHL', 'Tanzania': 'TZA', 'Fiji': 'FJI',
    'Hungary': 'HUN', 'Lithuania': 'LTU', 'Czech Republic': 'CZE', 'Zimbabwe': 'ZWE',
    'Belarus': 'BLR', 'China PR': 'CHN', 'Israel': 'ISR', 'Poland': 'POL',
    'Montenegro': 'MNE', 'Latvia': 'LVA', 'Vietnam': 'VNM', 'Bosnia and Herzegovina': 'BIH',
    'Serbia': 'SRB', 'Zambia': 'ZMB', 'South Korea': 'KOR', 'Syria': 'SYR',
    'Belgium': 'BEL', 'Canada': 'CAN', 'Moldova': 'MDA', 'Georgia': 'GEO',
    'Ukraine': 'UKR', 'Croatia': 'HRV', 'Luxembourg': 'LUX', 'Congo': 'COG',
    'Senegal': 'SEN', 'Tahiti': 'TAH', 'Slovakia': 'SVK', 'Hong Kong': 'HKG',
    'Papua New Guinea': 'PNG', 'Mozambique': 'MOZ', 'Iceland': 'ISL',
    'Tajikistan': 'TJK', 'Botswana': 'BWA', 'Solomon Islands': 'SLB',
    'Guinea': 'GIN', 'Malaysia': 'MYS', 'Togo': 'TGO', 'Albania': 'ALB',
    'Samoa': 'WSM', 'Gibraltar': 'GIB', 'Burundi': 'BDI', 'Cook Islands': 'COK',
    'Ethiopia': 'ETH', 'Kenya': 'KEN', 'Uganda': 'UGA', 'Belize': 'BLZ', 'Bahrain': 'BHR', 'Kosovo': 'KOS',
    'Oman': 'OMA', 'Faroe Islands': 'FRO', 'Gabon': 'GAB', 'Gambia': 'GAM', 'Burkina Faso': 'BFA', 'Malta': 'MLT',
    'Rwanda': 'RWA', 'Palestine': 'PLE', 'Swaziland': 'SWZ', 'Sierra Leone': 'SLE'
}

In [ ]:
sorted_abbreviations = dict(sorted(country_abbreviations.items()))

In [ ]:
sorted_abbreviations

#### adding rating for every league

In [ ]:
# Count appearances for each country
appearances = {}
league_ratings = {}

# Iterate through the original list
for country, rating in full_league_ratings:
    # If the country appears for the first time, add it to the appearances dictionary
    if country not in appearances:
        appearances[country] = 1
    else:
        # Increment the appearance count and update the country code
        appearances[country] += 1
    country_code = country_abbreviations.get(country, country)
    league_ratings[f'{country_code}{appearances[country]}'] = rating

In [ ]:
# check
league_ratings

In [ ]:
min_div = min(league_ratings.values())

division_rating = {}

# adding 
for key, value in divisions_abbreviations.items():
    division_rating[key] = league_ratings.get(value, min_div)

In [ ]:
# check
division_rating

In [ ]:
# making dataframe out of division_rating
division_df = pd.DataFrame(list(division_rating.items()), columns=['division', 'rating'])

In [ ]:
# peek
division_df.sample(5)

In [ ]:
# merging to main dataframe
df = pd.merge(df, division_df, on='division', how='left')
df = df.drop(columns=['division']).rename(columns={'rating': 'division_rating'})
df['division_rating'] = df['division_rating'].fillna(min_div)
df.sample(5)

### quantify nationality

In [ ]:
# Read the Excel file into a DataFrame
fifa_df = pd.read_excel('../raw_data/Fifa_index.xlsx')

In [ ]:
# Rename 'Column1' to 'Code'
fifa_df.rename(columns={'Column1': 'nat'}, inplace=True)

# Drop 'Previous Points' and '+/-' columns
fifa_df.drop(['RK','Team','Previous Points', '+/-'], axis=1, inplace=True)

# peek
fifa_df.head()

In [ ]:
min_nat = min(fifa_df["Total Points"])

In [ ]:
# Merge the two DataFrames on the common column 'Nationality' and 'Code'

df = pd.merge(df, fifa_df, on = 'nat', how='left')

df = df.rename(columns={'Total Points': 'nat_rating'})

df['nat_rating'] = df['nat_rating'].fillna(min_nat)

In [ ]:
# check
df.sample(5)

### quantify club

In [ ]:
df.club.nunique()

In [ ]:
# reducing number of values

# Identify less frequent values
threshold = 15  # Adjust as needed
value_counts = df['club'].value_counts()
rare_values = value_counts[value_counts < threshold].index

# Replace less frequent values with a common category
df['club'] = df['club'].replace(rare_values, 'Other')
df['club'] = df['club'].replace('', 'Other')

In [ ]:
df.club.nunique()

In [ ]:
# check
df.info()

In [ ]:
# Read the Excel file into a DataFrame
club_df = pd.read_excel('../raw_data/FichierRegression.xlsx')

In [ ]:
club_df = club_df[['Club','Club_point']]
club_df.drop_duplicates(inplace=True)

# changing special characters e.g.: Kylian Mbapp√É¬© --> Kylian Mbapp√©
club_df['Club'] = club_df['Club'].astype(str).apply(lambda x: x.encode('latin-1').decode('utf-8'))
club_df["Club"] = club_df["Club"].apply(str.strip)
club_df.rename(columns={'Club': 'club'}, inplace=True)

In [ ]:
# peek
club_df.sample(5)

In [ ]:
min_club = min(club_df['Club_point'])

In [ ]:
df = pd.merge(df, club_df, on = 'club', how='left')

df = df.rename(columns={'Club_point': 'club_rating'})

df['club_rating'] = df['club_rating'].fillna(min_club)

In [ ]:
df.head()

In [ ]:
df.info()

### onehotencode foot

In [ ]:
df["preferred foot"].unique()

In [ ]:
df['preferred foot'] = df['preferred foot'].replace("Right Only", "Right")
df['preferred foot'] = df['preferred foot'].replace("Left Only", "Left")

In [ ]:
conditions = [
    (df["left foot"] == "Very Strong") & (df["preferred foot"] == "Either"),
    (df["right foot"] == "Very Strong") & (df["preferred foot"] == "Either")
]

choices = ["Either_left", "Either_right"]

df["preferred foot"] = np.select(conditions, choices, default=df["preferred foot"])

In [ ]:
df = pd.get_dummies(df, columns=["preferred foot"], prefix="", prefix_sep="", dtype=int)

df.drop(columns = ['left foot', 'right foot'], inplace=True)

In [ ]:
df.head()

#  final cleaning

In [ ]:
df.info()

In [ ]:
# Fill NaN values in 'wage' with the minimum value
min_wage = df['wage'].min()
df['wage'].fillna(min_wage, inplace=True)

# Fill NaN values in 'last trans. fee' with 0
df['last trans. fee'].fillna(0, inplace=True)

In [ ]:
# let second_minimum value become minimum value
min_value = df['value'].min()
second_min_value = df['value'][df['value'] != min_value].min()
df['value'].replace(min_value, second_min_value, inplace=True)

In [ ]:
# cleaning column names

df.rename(str.lower, axis='columns', inplace = True)
df.rename(str.strip, axis='columns', inplace = True)

In [ ]:
df.info()

# export

In [ ]:
df.to_csv('../raw_data/clean_data.csv', index=False)

In [ ]:
df[df['name'] == '']

In [ ]:
# Assuming df is your DataFrame and 'name' is the column containing names
# Assuming df is your DataFrame and 'name' is the column containing names
unique_names = df.groupby('name').filter(lambda x: len(x) == 1)['name'].unique()
unique_names

In [ ]:
len(unique_names)

In [ ]:
df[['name', 'value']].sample(20)